### ISSUE TITLE
Reuse the checkpoint

### ISSUE THREAD

**Issue by sweetkurapika** [gablg1/ORGAN#8]
Hi, thank you for this great work.
After training the model, how can we load it again and reuse it for generating new molecules (e.g. SMILES)? I hope you can tell me how write a program for reusing it, thanks in advance

**Comment by couteiral** [comment]
Hi @sweetkurapika.

The last version of ORGAN has an interface very similar to (in fact, inspired in) ORGANIC, so I refer you [to my previous comments](https://github.com/aspuru-guzik-group/ORGANIC/issues/1).
